GET http://localhost:3145/tasks/all

###

GET http://localhost:3145/tasks

###

GET http://localhost:3145/tasks?date=2026-06-22
Content-Type: application/json

###

GET http://localhost:3145/tasks/7

###
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name" : "Сходить в зал за бумагами",
    "Description" : "После зайти к бабушке",
    "PriorityId" :3,
    "DayOrder" : 1,
    "Date" : "2026-06-16"
}

###

PUT http://localhost:3145/tasks/7
Content-Type: application/json

{
    "Name" : "Доделать ToDo бэк",
    "isCompleted": true,
    "Description" : "",
    "PriorityId" :3,
    "DayOrder" : 1,
    "Date" : "2026-06-18"
}

###

DELETE http://localhost:3145/tasks/5

###

GET http://localhost:3145/quotes/today

###

GET http://localhost:3145/api

###

GET http://localhost:3145/quotes/today

###

GET http://localhost:3145/tasks/on_week_status?startWeekDay=2026-06-15

### --- ПОНЕДЕЛЬНИК (22 ИЮНЯ) ---
### Задача 1: Высокий приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Повторить теоремы к коллоквиуму",
    "Description": "Ролль, Лагранж, Коши и Вейерштрасс. Нужно знать формулировки и доказательства",
    "PriorityId": 3,
    "DayOrder": 1,
    "Date": "2026-06-22",
    "IsCompleted": false
}

### Задача 2: Средний приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Дописать PATCH эндпоинт для задач",
    "Description": "Связать фронтенд с бэкендом для обновления IsCompleted в БД",
    "PriorityId": 2,
    "DayOrder": 2,
    "Date": "2026-06-22",
    "IsCompleted": false
}

### Задача 3: Низкий приоритет (Уже выполнена)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Обновить конфигурацию Obsidian",
    "Description": "Проверить ссылки в Map of Content",
    "PriorityId": 1,
    "DayOrder": 3,
    "Date": "2026-06-22",
    "IsCompleted": true
}


### --- ВТОРНИК (23 ИЮНЯ) ---
### Задача 1: Высокий приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Подготовка к хакатону",
    "Description": "Собрать базовый шаблон Flutter + .NET Minimal API",
    "PriorityId": 3,
    "DayOrder": 1,
    "Date": "2026-06-23",
    "IsCompleted": false
}

### Задача 2: Средний приоритет (Уже выполнена)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Кардио тренировка",
    "Description": "Бег 5 км в спокойном темпе",
    "PriorityId": 2,
    "DayOrder": 2,
    "Date": "2026-06-23",
    "IsCompleted": true
}


### --- СРЕДА (24 ИЮНЯ) ---
### Задача 1: Низкий приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Купить продукты",
    "Description": "Овсянка, куриное филе, бананы, молоко",
    "PriorityId": 1,
    "DayOrder": 1,
    "Date": "2026-06-24",
    "IsCompleted": false
}


### --- ЧЕТВЕРГ (25 ИЮНЯ) ---
### На этот день сделаем много задач, чтобы потестить скролл и прогресс-бар

### Задача 1: Высокий приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Финальный прогон теории к тесту",
    "Description": "Векторная геометрия и пределы",
    "PriorityId": 3,
    "DayOrder": 1,
    "Date": "2026-06-25",
    "IsCompleted": false
}

### Задача 2: Средний приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Почистить кэш IDE",
    "Description": "Проверить стабильность сборки Flutter",
    "PriorityId": 2,
    "DayOrder": 2,
    "Date": "2026-06-25",
    "IsCompleted": false
}

### Задача 3: Средний приоритет (Уже выполнена)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Созвон по проекту ToDo",
    "Description": "Обсудить дизайн карточек с Sonet",
    "PriorityId": 2,
    "DayOrder": 3,
    "Date": "2026-06-25",
    "IsCompleted": true
}

### Задача 4: Низкий приоритет (Уже выполнена)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Разобрать почту",
    "Description": "Удалить спам, ответить на важные учебные уведомления",
    "PriorityId": 1,
    "DayOrder": 4,
    "Date": "2026-06-25",
    "IsCompleted": true
}


### --- ПЯТНИЦА (26 ИЮНЯ) ---
### Задача 1: Высокий приоритет (Активная)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Сдать коллоквиум по математике",
    "Description": "Главное событие недели, коэффициент 3",
    "PriorityId": 3,
    "DayOrder": 1,
    "Date": "2026-06-26",
    "IsCompleted": false
}


### --- СУББОТА (27 ИЮНЯ) ---
### Пусть суббота будет полностью разгрузочной и выполненной (100% прогресс)

### Задача 1: Средний приоритет (Уже выполнена)
POST http://localhost:3145/tasks
Content-Type: application/json

{
    "Name": "Выспаться",
    "Description": "Сон минимум 9 часов без будильника",
    "PriorityId": 2,
    "DayOrder": 1,
    "Date": "2026-06-27",
    "IsCompleted": true
}


### --- ВОСКРЕСЕНЬЕ (28 ИЮНЯ) ---
### Оставим день пустым для проверки состояния "No tasks found"